package com.example.its.aifeedback.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Domain model representing a learning recommendation for a student.
 * This is NOT a JPA entity - it's a value object generated by the AI engine
 * to suggest next learning steps.
 * 
 * Contains:
 * - The student this recommendation is for
 * - The next topic they should study
 * - An explanation of why this topic is recommended
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class LearningRecommendation {

    private Long studentId;

    private String nextTopic;

    private String explanation;
}
